name: learning_wonderland
description: A new Flutter project for teaching first-grade students reading and writing.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  go_router: ^13.0.1
  drift: ^2.13.0
  path_provider: ^2.1.1
  path: ^1.8.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  lottie: 3.3.1
  firebase_analytics: ^10.10.7
  flutterfire_cli: ^1.3.1
  equatable: ^2.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.13.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/sanrio_characters/static/
    - assets/sanrio_characters/animated/
    - assets/images/fatmasu_profile_photos/
    - assets/images/backgrounds/
    - assets/images/ui_elements/
    - assets/images/rewards/
    - assets/icons/custom/
    - assets/lottie_animations/
