name: learning_wonderland
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_analytics: ^12.0.1

  # Flutter destek paketleri
  path_provider: ^2.1.5

  # Routing
  go_router: ^16.2.1

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Fonts
  google_fonts: ^6.3.1

  # Local database
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39

dev_dependencies:
  build_runner: ^2.7.2
  drift_dev: ^2.28.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sanrio_characters/static/
    - assets/sanrio_characters/animated/
    - assets/images/fatmasu_profile_photos/
    - assets/images/backgrounds/
    - assets/images/ui_elements/
    - assets/images/rewards/
    - assets/icons/custom/
    - assets/lottie_animations/
