// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfgJYCL-e3pP6uYXHRd5UhHT6ap7lgjkc',
    appId: '1:843942874163:web:0dd4ae3a5828f6b1e2a746',
    messagingSenderId: '843942874163',
    projectId: 'learning-wonderland',
    authDomain: 'learning-wonderland.firebaseapp.com',
    storageBucket: 'learning-wonderland.firebasestorage.app',
    measurementId: 'G-P3V8L1DZPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77kFAOlDfkpYkX0Cv9A30AnYqSykYv4Q',
    appId: '1:843942874163:android:1e1d68ebca4164a0e2a746',
    messagingSenderId: '843942874163',
    projectId: 'learning-wonderland',
    storageBucket: 'learning-wonderland.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY8Xs7YDYvsEwH9rRNj0C5WJc1Ua_XuuA',
    appId: '1:843942874163:ios:5501846191b9a2d7e2a746',
    messagingSenderId: '843942874163',
    projectId: 'learning-wonderland',
    storageBucket: 'learning-wonderland.firebasestorage.app',
    iosBundleId: 'com.learningwonderland.app.learningWonderland',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY8Xs7YDYvsEwH9rRNj0C5WJc1Ua_XuuA',
    appId: '1:843942874163:ios:5501846191b9a2d7e2a746',
    messagingSenderId: '843942874163',
    projectId: 'learning-wonderland',
    storageBucket: 'learning-wonderland.firebasestorage.app',
    iosBundleId: 'com.learningwonderland.app.learningWonderland',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfgJYCL-e3pP6uYXHRd5UhHT6ap7lgjkc',
    appId: '1:843942874163:web:30b5d8c50d2188dfe2a746',
    messagingSenderId: '843942874163',
    projectId: 'learning-wonderland',
    authDomain: 'learning-wonderland.firebaseapp.com',
    storageBucket: 'learning-wonderland.firebasestorage.app',
    measurementId: 'G-JVLKNPFRCQ',
  );
}
